- regExp: ".*\\.ts+$"
  labels: ["typescript"]
- regExp: "(.*\\.yml+$|.*\\.properties+$)"
  labels: ["configuration"]
- regExp: ".*\\.sql+$"
  labels: ["database", "critical"]
- regExp: ".*\\.md+$"
  labels: ["documentation"]
- regExp: ".*\\.java+$"
  labels: ["code"]
- regExp: ".*\\.png+$"
  labels: ["images"]
- regExp: "^(build\\.gradle)$"
  labels: ["gradle"]
- regExp: ".*\\.(zip|jar|war|ear)+$"
  labels: ["artifact", "invalid"]
