name: Code quality control

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build -x test
    - uses: actions/upload-artifact@v1
      with:
        name: builtArtifacts
        path: build/libs

  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/download-artifact@v1
      with:
        name: builtArtifacts
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test Api with gradle
      run: ./gradlew testAllAPI
    - name: Test BDD with gradle
      run: ./gradlew testAllBDD
