name: release flow

on:
  push:
    branches:
      - versionTest

jobs:
  bumpdVersion:
    # Bumping
    # Manual Bumping: Any commit message that includes
    #  - #major,
    #  - #minor
    #  - #patch
    # will trigger the respective version bump.
    # If two or more are present, the highest-ranking one will take precedence.
    # Automatic Bumping:
    # - If no #major, #minor or #patch tag is contained in the commit messages,
    # it will bump whichever DEFAULT_BUMP is set to (which is minor by default).
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: versionTest
        DEFAULT_BUMP: patch
  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{steps.bumpdVersion.new_tag}}
          release_name: Release ${{steps.bumpdVersion.new_tag}}
          body: |
            Auto Commit
            - First Change
            - Second Change
          draft: false
          prerelease: false
